apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      securityContext:
        fsGroup: 1000 # jenkins user gid(volumemounts permission)
      containers:
      - name: master
        image: gcr.io/YOUR_PROJECT/jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: GOOGLE_APP_CLIENT_ID
          value: ""
        - name: GOOGLE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: google-app-secret
        - name: GOOGLE_ACCOUNT_DOMAIN
          value: ""
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
      volumes:
      - name: jenkins-home
        gcePersistentDisk:
          pdName: "jenkins-home"
          fsType: ext4
